global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-autodesk-forge-bim360-integration
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-autodesk-forge-bim360-integrationt1:
    parameter_input: quickstart-autodesk-forge-bim360-integration-example-params1.json
    template_file: quickstart-autodesk-forge-bim360-integration-example1.template
  quickstart-autodesk-forge-bim360-integrationt2:
    parameter_input: quickstart-autodesk-forge-bim360-integration-example-params2.json
    template_file: quickstart-autodesk-forge-bim360-integration-example2.template
